Kalender-Termine auf Webseite anzeigen
TechAachen/Webseite-Jekyll pull request #39
Opened 2022-01-30 15:40 UTC by rleh

Ich hab da mal was gebastelt...

Fixes #37

2022-01-30 15:41 UTC, rleh commented
![image](https://user-images.githubusercontent.com/2820734/151706489-51c57e85-e860-4c9e-a8f7-86e0838ab6c5.png)

2022-02-16 19:42 UTC, kboettger requested changes
9/10

2022-02-16 19:42 UTC, kboettger commented on _data/events.yml
> +    Beim Kompetenztreffen Embedded Systems tauschen sich die Studierenden der verschiedenen Teams über ihr Technologien und Tools aus.
```suggestion
    Beim Kompetenztreffen Embedded Systems tauschen sich die Studierenden der verschiedenen Teams über ihre Technologien und Tools aus.
```

2022-02-16 19:42 UTC, kboettger commented on _data/events.yml
> +    Wenn sich gegenseitig nicht weitergeholfen werden kann organisiert TechAachen Workshops und Trainings mit externen Referenten.
```suggestion
    Wenn sich gegenseitig nicht weitergeholfen werden kann organisiert der TechAachen Workshops und Trainings mit externen Referent*innen.
```

2022-02-16 19:43 UTC, kboettger approved these changes

2022-02-16 19:50 UTC, merged