Add time and location for Jahreshauptversammlung 2024
TechAachen/Webseite-Jekyll pull request #93
Opened 2023-11-30 20:00 UTC by joelsa

Add time and location for Jahreshauptversammlung 2024

2023-11-30 20:13 UTC, mat-kie requested changes

2023-11-30 23:16 UTC, joelsa commented
@mat-kie Jetzt passts.

2023-12-25 15:03 UTC, rleh approved these changes

2023-12-26 12:20 UTC, rleh commented
Ich hab mal die Konflikte aufgelöst und außerdem noch ne Versammlung am 10.01. zum Kalender hinzugefügt.
Merge? @mat-kie @TheLeo22?

2024-01-04 21:28 UTC, merged